name: "Hello world workflow"

on: 
  push:
    branches:
      - master
      - production
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print hello world"
        run: echo "Hello World"

      - name: "Print current date"
        run: date